version: '3.0'
services:
  mobilitydb:
    #image: It should be a link: mobilitydb/mobilitydb:11-2.5-master, so I use the below build code instead. 
    build: 
      context: .
      dockerfile: Dockerfile    
    volumes:
      - mobilitydb-data:/var/lib/postgresql/data
    ports:
      - 5432:5432             
    environment:
      - POSTGRES_DB=mobilitydb
      - POSTGRES_USER=docker      
      - POSTGRES_PASSWORD=docker
    restart: on-failure

volumes:
  mobilitydb-data:    